server:
  port: 9999

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///xdb
  redis:
    host: localhost
    port: 6379



#    逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
#      逻辑删除为1，没有删除为0
      logic-delete-value: 1
      logic-not-delete-value: 0

  type-aliases-package: com.mo.*.entity

